# 系统配置
smgi:
  # 名称
  name: 测绘与地理空间中心门户
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/htht/，Linux配置 /home/htht/）
  profile: D:/smgi
  # 获取ip地址开关
  addressEnabled: true
# 服务配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8765
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    cn.htht: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 500MB
      # 设置总上传的文件大小
      max-request-size: 500MB

  elasticsearch:
    rest:
      uris: http://192.168.1.239:9200
  datasource:
    url: jdbc:mysql://192.168.1.239:3306/smgi?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    ## 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 5
    ## 最小连接池数量
    minIdle: 5
    ## 最大连接池数量 默认值 8
    maxActive: 20
    ## 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    maxWait: 60000
    ## 	有两个含义：1) Destroy线程会检测连接的间隔时间2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    ## 用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
    validationQuery: SELECT 1 FROM DUAL
    ## 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    ## 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    ## 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    ## 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    ## 属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  # redis 配置
  redis:
    # 地址
    host: 192.168.1.239
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
mapper:
  mappers: cn.htht.service.platform.portal.common.BasicMapper
  not-empty: false
  identity: MYSQL
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: cn.htht.service.platform.portal.entity.*
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
# token配置
token:
# 令牌自定义标识
  header: Authorization
# 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
# 令牌有效期（默认30分钟）
  expireTime: 30
  type: rsa
# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping:

# websocket 相关配置
websocket:
  url: ws://192.168.1.108:8765/websocket/

minio:
  endpoint: http://192.168.1.239:9009/
  accessKey: sldeveloper
  secretKey: sldeveloper
  allow-file-type: jpg,png,jpeg,zip,rar,doc,docx,xls,xlsx,img,iso
  chunk-upload-expiry-second: 86400
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes:
  # 匹配链接
  urlPatterns: /system/*,/portal/*,/manager/*

file:
  show:
    url:
      pic: http://192.168.1.108:8765/file/show/
      file: http://192.168.1.108:8765/file/download/


